model:
  dualrec:
    class_path: src.model.DualRecModel
    init_args:
      d_model: 64
      d_head: 8
      n_head: 8
      d_inner: 64
      seg_len: 50
      layer_norm_eps: 1e-12
      dropout: 0.5
      activation_type: 'gelu'
      clamp_len: -1
      n_layer: 2
      num_items: 12101
      device: 'cuda'
      initializer_range: 0.02
  lr: 0.001
  weight_decay: 1e-4
  aux_factor: 0.1


data:
  class_path: src.datamodule.DualRecDataModule
  init_args:
    dataset_code: 'Beauty'
    data_type: "seq"
    seg_len: 50
    num_train_seg: 1
    num_test_seg: 1
    pred_prob: 0.9
    num_workers: 4
    test_negative_sampler_code: fixed
    test_negative_sample_size: 99
    train_batch_size: 256
    val_batch_size: 256
    test_batch_size: 256

trainer:
  default_root_dir: logs/beauty
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'Val:MRR'
        patience: 10
        mode: max  
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: "Val:MRR"
        verbose: true
        save_top_k: 1
        mode: max
  max_epochs: 150
  gradient_clip_val: 5.0
  gpus: '0,'
  accelerator: ddp